* Instalación
ROS funciona para el sistema operativo GNU/Linux y alguna distribución
de linux es requerida para utilizarlo. Las diferentes versiones de ROS
aumentan poco a poco el soporte de las diferentes distribuciones, pero
Ubuntu tiene el mejor soporte, por lo que se recomienda usar Ubuntu
LTS (Long term support o soporte de tiempo extendido), al tiempo de
escritura el LTS de Ubuntu es 16.04 y tiene soporte hasta
el 2018. Para información actualizada ver la [[http://wwww.ros.org/reps/rep-0003.html][páguna de soporte de
plataformas oficial]].

Para empezar a usar ROS no es necesario instalar Ubuntu en la
computadora, se puede usar una maquina virtual (vm) y se cubrirá como
instalar Ubuntu en una usando virtualbox. Ciertas partes
de ROS, en particular el simulador, es muy pesado y requiere de acceso
a hardware especializado como el GPU el cual no se encuentra
disponible en una maquina virutal, por lo que para uso avanzado de ROS
y el simulador es necesario instalar ROS en la computadora física, ya
que el simulador corre muy lento en una maquina virutal.

En esta guía se va a explicar dos maneras de instalar Ubuntu y ROS en
una maquina virtual. Una usando Vagrant el cual es una herramienta
para crear maquinas virtuales automáticamente, la usaremos para crear
una maquina que ya tiene Ubuntu y ROS instalado y esta lista para
continuar, el otro método que se explicará es como crear la maquina
virtual de manera manual, instalar Ubuntu y luego instalar ROS. Las
instrucciones de instalación de ROS y Ubuntu también son válidas fuera
de maquinas virtuales.

Si ya está usando Ubuntu puede saltar a la sección de instalación de
ROS. de esta guía.

** Instalación de Virtualbox
Virtualbox es un programa para crear y manejar maquinas virtuales, la
usaremos para correr Ubuntu sin necesidad de instalarlo en nuestras
computadoras directamente.

*** Descarga:
Para descargar Virtualbox visite la página oficial y seleccione el
sistema operativo que esta utilizando.
*Nota para linux:* Es probable que virtualbox se encuentre en los
repositorios de software de su distribución.

Página oficial de descarga:
[[https://www.virtualbox.org/wiki/Downloads][https://www.virtualbox.org/wiki/Downloads]]

Una vez descargado siga las instrucciones del instalador.


** Instalación con Vagrant
Vagrant es una herramienta para crear maquinas virtuales de manera
automática. Con ella un archivo llamado /Vagrantfile/ que se encuentra
en la raíz del repositorio de github de estas guías se creara una vm
con todo lo necesario pre-instalado.

*** Descarga
Descargue vagrant de la siguiente página:

[[https://www.vagrantup.com/downloads.html][https://www.vagrantup.com/downloads.html]]

*Importante:* Asegúrese de tener virtualbox ya instalado, Vagrant
requiere de virtualbox para funcionar.

Siga las instrucciones de instalación correspondientes.

*** Abrir una consola
Lo único que resta usar vagrant, para ello debemos de usar una
consola.

Navegue con su manejador de archivos hasta la carpeta que contenga en
Vagrantfile, luego para abrir la consola:

- Windows: Sostenga shift y presione con el botón derecho del ratón
  espacio en blanco dentro de la carpeta y selección "Abrir una
  Ventana de Comandos Aquí" del menú.

- OSX: La opción para abrir una terminal en el folder esta
  dehabilitada por defecto, para habilitarla vaya a preferencias del
  sistema > Teclado > Shortcuts > Servicios y marque la casilla de
  "Nueva terminal en folder". Ahora puede dar click derecho con el
  ratón y seleccionar abrir terminal

- Linux: Presione el botón derecho del ratón en espacio en blanco
  dentro del directorio y seleccione la opción "Abrir terminal aquí"

*** Creación de la VM
Escriba "vagrant up" en la consola y presione enter. Luego vagrant
bajará una maquina virtual con Ubuntu y le instalara ROS de manera
automática.

Una vez que haya terminado puede abrir virtualbox y seleccionar su
nueva maquina virtual con ROS. El usuario es vagrant y la contraseña
es vagrant.

Si se utiliza vagrant ya ha terminado y esta listo para aprender ROS,
puede saltarse el resto de la guía de instalación.
** Creación manual en maquina virtual

** Instalación de Ubuntu

** Instalación de ROS en Ubuntu
